### ISSUE TITLE
Usage instructions

### ISSUE THREAD

**Issue by kris-rowe** [argonne-lcf/occa#2]
Provide documentation on how to build and run a libocca application.

Currently the [README](https://github.com/libocca/occa#use) gives basic details on using the cmake package files and env modules.

## Todo

- [ ] Create RUN.md
- [ ] How to build a downstream application
  - [ ] Propagation of dependencies 
- [ ] How to run a downstream application
  - [ ] Table of environment variables with descriptions
- [ ] Kernel caching
- [ ] Debugging/troubleshooting
  - [ ] Common issues
  - [ ] Best practices
