### ISSUE TITLE
Runtime API

### ISSUE THREAD

**Issue by kris-rowe** [argonne-lcf/occa#4]
Update the [high-level documentation](https://github.com/argonne-lcf/occa/blob/main/docs/guide/occa/introduction.md) on OCCA runtime concepts. This should only cover an overview of core concepts and not dive into the specific details of member function API, which is covered elsewhere and generated automatically.

Combine/refactor the existing markdown files for this section as needed.

## Todo

- [ ] Streams
- [ ] StreamTags
- [ ] Synchronization
  - [ ] Implicit&mdash;e.g., host-to-device memory copies
  - [ ] Explicit&mdash;e.g., via currents stream, streamTags
- [ ] Host-side thread safety
- [ ] Comparison/mapping of occa concepts to backend programming models
