### ISSUE TITLE
OKL Attributes

### ISSUE THREAD

**Issue by kris-rowe** [argonne-lcf/occa#5]
Update [existing documentation](https://github.com/argonne-lcf/occa/tree/main/docs/guide/okl) on OKL.

Combine and refactor existing markdown files as needed.

## Todo

- [x] Review which [OKL attributes](https://github.com/argonne-lcf/occa/tree/main/src/occa/internal/lang/builtins/attributes) are missing documentation
- [ ] Kernels
  - [ ] `@kernel`
  - [ ] Kernel arguments
    - [ ] `@restrict`
    - [ ] `@globalPtr`
    - [ ] `@implicitArg`(?!)
  - [ ] Device functions 
- [ ] Loops
  - [ ] `@inner`, `@outer`
  - [ ] `@tile`
  - [ ] `@maxInnerDims`
- [ ] Memory spaces
  - [ ] `@globalPtr`
  - [ ] `@shared`
  - [ ] `@exclusive`
  - [ ] Default spaces
- [ ] Barriers
  - [ ] Auto insertion between `@inner` loop-blocks
  - [ ] Explicit barriers (`@barrier`)
  - [ ] `@nobarrier` 
- [ ] Atomics (`@atomic`)
- [ ] `@dim`
- [ ] Glossary
- [ ] Table comparing how different OKL concepts map onto backend programming models
